DROP TABLE IF EXISTS BREED;
CREATE TABLE BREED(BREED_ID BIGINT PRIMARY KEY, NAME_BREED VARCHAR(255));
DROP TABLE IF EXISTS ANIMAL;
CREATE TABLE ANIMAL(ANIMAL_ID BIGINT PRIMARY KEY, NICK_NAME VARCHAR(255), WEIGHT DOUBLE, BREED_ID BIGINT);
DROP TABLE IF EXISTS OWNER;
CREATE TABLE OWNER(OWNER_ID BIGINT PRIMARY KEY, NICK_OWNER VARCHAR(255), ANIMAL_ID BIGINT);